### ISSUE TITLE
Connect to ETH eip155:1

### ISSUE THREAD

**Issue by DorenBoust** [AakifNadeem/WalletConnectSwiftUIV2#1]
First of all great package, help me a lot!
sec, can you add option to choose/add networks?
now you only add polygon eip155:137 and I want to add eth eip155:1.

with Metamask Its not really matter but with ledger not...

thanks

**Comment by AakifNadeem** [comment]
Sure @DorenBoust I'll add support to add custom chains.

**Comment by DorenBoust** [comment]
Thanks

**Comment by AakifNadeem** [comment]
Added custom ChainIds Support
